NewsPaper_3/NewsPaper_3/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
]

NewsPaper_3/news/urls.py
from django.urls import path
from .views import NewsListView, NewsDetailView, add_news, search_news, edit_news, delete_news

app_name = 'news'

urlpatterns = [
    path('', NewsListView.as_view(), name='news_list'),
    path('<int:pk>/', NewsDetailView.as_view(), name='news_detail'),
    path('add/', add_news, name='add_news'),
    path('search/', search_news, name='search_results'),
    path('<int:pk>/edit/', edit_news, name='edit_news'),
    path('<int:pk>/delete/', delete_news, name='delete_news'),
]

NewsPaper_3/protect/urls.py
from django.urls import path
from . import views

app_name = 'protect'

urlpatterns = [
    path('protected/', views.protected_view, name='protected_view'),
]

NewsPaper_3/news/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

class News(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    pub_date = models.DateTimeField('date published')
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True)

    def __str__(self):
        return self.title

    def get_short_text(self):
        return " ".join(self.text.split()[:20]) + "..."

    def get_formatted_date(self):
        return self.pub_date.strftime("%d.%m.%Y")

    def get_absolute_url(self):
        return reverse('news:news_detail', args=[str(self.id)])

NewsPaper_3/protect/models.py
from django.db import models

# Create your models here.

NewsPaper_3/news/forms.py
from django import forms
from .models import News

class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['title', 'text', 'pub_date', 'author']

NewsPaper_3/news/views.py
# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from .models import News
from .forms import NewsForm
from django.db.models import Q
from django.core.paginator import Paginator

class NewsListView(ListView):
    model = News
    template_name = 'news_list.html'
    context_object_name = 'news_list'
    ordering = ['-pub_date']
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.order_by('-pub_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        count = self.request.GET.get('count', self.paginate_by)
        paginator = Paginator(context['news_list'], count)
        page = self.request.GET.get('page')
        context['news_list'] = paginator.get_page(page)
        context['count'] = int(count)
        return context

class NewsDetailView(DetailView):
    model = News
    template_name = 'news_detail.html'
    context_object_name = 'news'

def add_news(request):
    if request.method == 'POST':
        form = NewsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('news:news_list')
    else:
        form = NewsForm()
    return render(request, 'add_news.html', {'form': form})

def edit_news(request, pk):
    news = get_object_or_404(News, pk=pk)
    if request.method == 'POST':
        form = NewsForm(request.POST, instance=news)
        if form.is_valid():
            form.save()
            return redirect('news:news_list')
    else:
        form = NewsForm(instance=news)
    return render(request, 'edit_news.html', {'form': form})

def delete_news(request, pk):
    news = get_object_or_404(News, pk=pk)
    if request.method == 'POST':
        news.delete()
        return redirect('news:news_list')
    return render(request, 'delete_news.html', {'news': news})
def search_news(request):
    title = request.GET.get('title', '')
    author = request.GET.get('author', '')
    date = request.GET.get('date', '')

    search_q = Q()
    if title:
        search_q |= Q(title__icontains=title)
    if author:
        search_q |= Q(author__username__icontains=author)
    if date:
        search_q |= Q(pub_date__gt=date)

    news_list = News.objects.filter(search_q)
    return render(request, 'search_news.html', {'news_list': news_list})

NewsPaper_3/protect/views.py
ffrom django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def protected_view(request):
    return render(request, 'protected_view.html')

NewsPaper_3/news/templates/add_news.html
<!DOCTYPE html>
<html>
<head>
    <title>Добавление новостей</title>
</head>
<body>
    <h1>Добавить новость</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Добавить">
    </form>
</body>
</html>

NewsPaper_3/news/templates/default.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Мои новости{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div id="header">
        <!-- Здесь шапкa сайта -->
    </div>

    <div id="content">
        <form action="{% url 'news:search_results' %}" method="get" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Поиск" name="q">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Найти</button>
        </form>
        <a href="{% url 'news:add_news' %}" class="btn btn-primary my-2">Добавить новость</a>
        {% block content %}
        {% endblock %}
    </div>

    <div id="footer">
        <!-- Здесь подвал сайта -->
    </div>
</body>
</html>

NewsPaper_3/news/templates/delete_news.html
{% extends 'default.html' %}

{% block content %}
    <h1>Delete News</h1>
    <p>Are you sure you want to delete this news?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>
{% endblock %}

NewsPaper_3/news/templates/edit_news.html
{% extends 'default.html' %}

{% block content %}
    <h1>Edit News</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

NewsPaper_3/news/templates/news_detail.html
{% extends 'default.html' %}
{% load custom_filters %}

{% block title %}{{ news.title }}{% endblock %}

{% block content %}
<h1>{{ news.title }}</h1>
<p>Дата публикации: {{ news.get_formatted_date }}</p>
<p>{{ news.text|censor }}</p>
{% endblock %}

NewsPaper_3/news/templates/news_list.html
{% extends 'default.html' %}

{% block content %}
<h1>Список новостей</h1>
<form action="" method="get">
        <label for="count">Количество новостей на странице:</label>
        <select name="count" id="count">
            <option value="5" {% if count == 5 %}selected{% endif %}>5</option>
            <option value="10" {% if count == 10 %}selected{% endif %}>10</option>
            <option value="15" {% if count == 15 %}selected{% endif %}>15</option>
            <!-- Добавьте другие варианты количества новостей, если необходимо -->
        </select>
        <button type="submit">Применить</button>
</form>

<p>Количество новостей: {{ news_list.paginator.count }}</p>

<ul>
    {% for news in news_list %}
    <li>
        <h2>{{ news.title }}</h2>
        <p>Дата публикации: {{ news.get_formatted_date }}</p>
        <a href="{% url 'news:news_detail' news.pk %}">Подробнее</a>
        <a href="{% url 'news:delete_news' news.pk %}" class="btn btn-danger">Удалить</a>
        <p>{{ news.get_short_text }}</p>
    </li>
    {% endfor %}
</ul>

<div class="pagination">
        <span class="step-links">
            {% if news_list.has_previous %}
                <a href="?count={{ count }}&page=1">&laquo; first</a>
                <a href="?count={{ count }}&page={{ news_list.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Страница {{ news_list.number }} из {{ news_list.paginator.num_pages }}.
            </span>

            {% if news_list.has_next %}
                <a href="?count={{ count }}&page={{ news_list.next_page_number }}">next</a>
                <a href="?count={{ count }}&page={{ news_list.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
</div>


{% endblock %}

NewsPaper_3/news/templates/search_news.html
{% extends 'default.html' %}

{% block content %}
<h1>Поиск новостей</h1>
<form action="{% url 'news:search_results' %}" method="get">
    <label for="search_title">По названию:</label>
    <input type="text" id="search_title" name="title">
    <br>
    <label for="search_author">По имени автора:</label>
    <input type="text" id="search_author" name="author">
    <br>
    <label for="search_date">Позже какой даты:</label>
    <input type="date" id="search_date" name="date">
    <br>
    <button type="submit">Искать</button>
</form>

<h2>Результаты поиска:</h2>
{% for news in news_list %}
    <div>
        <h3>{{ news.title }}</h3>
        <p>Автор: {{ news.author.username }}</p>
        <p>Дата публикации: {{ news.pub_date }}</p>
        <p>{{ news.text }}</p>
    </div>
{% empty %}
    <p>По вашему запросу ничего не найдено.</p>
{% endfor %}
{% endblock %}

NewsPaper_3/protect/templates/protected_view.html
{% extends 'base.html' %}

{% block content %}
    <h2>Добро пожаловать, {{ request.user.username }}!</h2>
    <p>Вы видите эту страницу, потому что вы аутентифицированный пользователь.</p>
{% endblock %}